# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fb3546dd331a5e4ec7cb7fe83918c283ab788550c2d1f77c1ad2e5618e39388fe978b91fa386d7cfefae3394982084f1794f007f5c6190c0d429829c5a8559d

test:
  secret_key_base: b1321d5a1038a6c01df5e9d05b3932f2000694b15b95f889921f3de3ebefffa8084d865ea502c76a5e8a3e6a9f087bf6f1955039a5d8c0141a51fdb0aa7ec008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
